development:
  adapter: postgresql
  encoding: unicode
  database: hexonomicon
  pool: 2
  username: lindseyjohnson
  password: Pickle22%

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>